import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export default defineSchema({
  users: defineTable({
    name: v.string(),
    email: v.string(),
    businessName: v.string(),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    website: v.optional(v.string()),
    logoUrl: v.optional(v.string()),
    paymentInstructions: v.string(),
    invoiceNotes: v.optional(v.string()),
    tokenIdentifier: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index("by_token", ["tokenIdentifier"]),
  clients: defineTable({
    name: v.string(),
    email: v.string(),
    address: v.optional(v.string()),
    hourlyRate: v.number(),
    userId: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index("by_user", ["userId"]),
  tasks: defineTable({
    description: v.string(),
    hours: v.number(),
    date: v.string(),
    client: v.optional(v.string()),
    clientId: v.optional(v.id("clients")),
    status: v.union(v.literal("pending"), v.literal("in-progress"), v.literal("completed")),
    hourlyRate: v.optional(v.number()),
    amount: v.optional(v.number()),
    invoiced: v.optional(v.boolean()),
    invoiceId: v.optional(v.id("invoices")),
    userId: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
  }),
  invoices: defineTable({
    number: v.string(),
    date: v.string(),
    dueDate: v.string(),
    clientId: v.id("clients"),
    status: v.union(v.literal("draft"), v.literal("sent"), v.literal("paid")),
    subtotal: v.number(),
    tax: v.number(),
    total: v.number(),
    notes: v.optional(v.string()),
    tasks: v.array(v.id("tasks")),
    userId: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
  }),
}) 